env:
  browser: true
  es2021: true
extends:
  - airbnb
  - eslint:recommended
  - plugin:react/recommended
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
rules:
  react/prop-types: 0
  import/extensions: 0
  no-param-reassign: 0
  react/function-component-definition: 0
  react/jsx-no-constructed-context-values: 0
  no-unused-vars: 0
  import/prefer-default-export: 0
  linebreak-style: 0
